# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'CocktailsCategories' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CocktailsCategories

	pod 'MBProgressHUD', '~> 1.2.0'
	pod 'SDWebImage'

end
