# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CocktailsCategories' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CocktailsCategories

	pod 'SnapKit', '~> 5.0.0'
	pod 'ProgressHUD'
	pod 'SDWebImage'

end
